---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build and Test Pull Request
on:
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  STAGE: dev
  DD_VERSION: ${{ github.sha }}

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    environment:
      name: dev
      deployment: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Go Version
        run: go version
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup python (swagger tooling)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: cla-backend-go/swagger/requirements.txt
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure Git to clone private Github repos
        run: git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER_GITHUB }}

      - name: Add OS Tools
        run: sudo apt update && sudo apt-get install file -y

      - name: Go Setup
        working-directory: cla-backend-go
        run: make clean setup

      - name: Go Dependencies
        working-directory: cla-backend-go
        run: make deps

      - name: Go Swagger Generate
        working-directory: cla-backend-go
        run: make swagger

      - name: Go Build
        working-directory: cla-backend-go
        run: |
          make build-lambdas-linux build-functional-tests-linux

      - name: Go Test
        working-directory: cla-backend-go
        run: make test

      - name: Go Lint
        working-directory: cla-backend-go
        run: make lint

      - name: Go Setup CLA Legacy Backend
        working-directory: cla-backend-legacy
        run: |
          go mod tidy

      - name: Go Build CLA Legacy Backend
        working-directory: cla-backend-legacy
        run: |
          make lambdas

      - name: Go Test CLA Legacy Backend
        working-directory: cla-backend-legacy
        run: go test ./...

      - name: Go Lint CLA Legacy Backend
        working-directory: cla-backend-legacy
        run: make lint
