---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Yarn Python Backend Dependency Audit

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - dev
    paths:
      - "cla-backend/package.json"
      - "cla-backend/yarn.lock"
      - ".github/workflows/yarn-scan-backend-pr.yml"

jobs:
  yarn-scan-backend-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup
        run: yarn install
#       - name: Yarn Audit
#         working-directory: cla-backend
#         run: |
#           yarn audit
      - name: Yarn Audit
        working-directory: cla-backend
        run: |
          yarn audit --json > audit.json || true
          node ../scripts/yarn-audit-filter.mjs audit.json ../.yarn-audit-allowlist.json
